### ISSUE TITLE
[Speedtest] Speedtest failed

### ISSUE THREAD

**Issue by princeberenger** [raycast/extensions#1458]
# Extension – [Speedtest](https://github.com/raycast/extensions/tree/66e9a870cc77750c7476f9411de2586c5c06f52d/extensions/speedtest/)
Author: @tonka3000
![CleanShot 2022-04-20 at 21 52 47@2x](https://user-images.githubusercontent.com/85639913/164543574-f45624ab-9564-4334-bf96-1532cb4fe316.png)

## Description
Getting "spawn Unknown system error -86" everytime I run the extension.

## Steps To Reproduce

1. Open Raycast
2. Launch Speedtest

### Raycast version
Version: 1.33.1

**Comment by tonka3000** [comment]
Try to clear the local cache via "Clear CLI Cache" action and restart Speedtest.

**Comment by tonka3000** [comment]
Also check if Rosetta is installed and active on your system.

**Comment by princeberenger** [comment]
Hi @tonka3000,

I tried the command and restart Raycast then the extension but it still doesn't work. Yes I have Rosetta installed on my Mac

**Comment by tonka3000** [comment]
Maybe `softwareupdate --install-rosetta` fix the problem. Users which have the same error message with other applications mention that this sometimes help to fix the issue.

**Comment by princeberenger** [comment]
The issue is fixed. Thanks for your help :)

**Comment by djpowers** [comment]
I was running into this same issue (also mentioned in #563).

I'm assuming the Speedtest.net CLI still relies on some Intel-only dependencies? I'd love to be able to run this without installing Rosetta, but it sounds like that might be determined by @teamookla.

Until then though I'm wondering if it might be worth noting this requirement in the README.

**Comment by tonka3000** [comment]
Hi @djpowers ,

Can you try to install Speedtest cli via homebrew. Maybe this is already M1 enabled. I have no M1 Mac and I can not test that easily.

Adding a notice to the README is a good idea.

**Comment by djpowers** [comment]
Hi @tonka3000, I just installed the CLI via homebrew by following these instructions: https://www.speedtest.net/apps/cli

I was not prompted to install Rosetta 2 as part of the process, and was able to successfully run a test after accepting the license terms. (Trying to install a known Intel-only cask from homebrew is still failing, for comparison.)

The extension is still failing for me with the same error.

**Comment by tonka3000** [comment]
@djpowers The only option to get it to work is to active open with Rosetta for Raycast itself as mentioned above. I assume that MacOS don't support indirect automatic activation of Rosetta. Raycast => NodeJS => speedtest-cli.
