### ISSUE TITLE
[JetBrains Toolbox Recent Projects] TypeError: Cannot read properties of undefined (reading '0') in b8:util.ts:235:56

### ISSUE THREAD

**Issue by vasayxtx** [raycast/extensions#15836]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Raycast Version

1.87.5

### macOS Version

14.7.1

#### Error:
```
TypeError: Cannot read properties of undefined (reading '0')

b8:util.ts:235:56

---
232:   if (tool.toolName === undefined) {
233:     return [];
234:   }
235:   const directoryPatterns = channel.history?.toolBuilds[0]?.tool?.intelliJProperties?.directoryPatterns ?? [];
236:   const recentProjectsFilenames =
237:     channel.history?.toolBuilds[0]?.tool?.intelliJProperties?.recentProjectsFilenames ?? [];
238:   if (directoryPatterns.length === 0 || recentProjectsFilenames.length === 0) {
---

recent.js:52:1759
    at async Promise.all (index 0)
async cl:recent.js:52:1262
```

### Steps To Reproduce

1. Open GoLand 2024.3.1
2. Open Raycast
3. Type "Search Recent Projects", and press enter.
4. See "Something went wrong" error.

**Comment by gdsmith** [comment]
Fixed in #15838

**Comment by bigplayer-ai** [comment]
The Raycast JetBrains Toolbox extension throws a TypeError when trying to fetch or display recent projects. The issue occurs after setting the correct JetBrains shell scripts path.

Steps to Reproduce
	1.	Enable Shell Scripts in JetBrains Toolbox with the following path, and insert the shell scripts location escaped into raycast ( I think this also must be mentioned in the tip over):
~/Library/Application\ Support/JetBrains/Toolbox/scripts


	2.	Confirm the shell scripts are present:

ls -la ~/Library/Application\ Support/JetBrains/Toolbox/scripts

Output:

-rwxr-xr-x@ 1 user  staff  421 clion
-rwxr-xr-x@ 1 user  staff  428 idea
-rwxr-xr-x@ 1 user  staff  422 pycharm


	3.	Verify that the recentProjects.xml files exist for JetBrains IDEs:

ls -la ~/Library/Application\ Support/JetBrains/*/options/recentProjects.xml


	4.	Set the Shell Scripts Location in Raycast extension preferences to the correct path:

~/Library/Application\ Support/JetBrains/Toolbox/scripts


	5.	Use the extension to search for recent JetBrains projects.

Expected Behavior

The extension should list the recent JetBrains IDE projects.

Actual Behavior

An unhandled exception occurs, and no projects are displayed. The error message in the logs is:

TypeError: Cannot read properties of undefined (reading '0')

b8:util.ts:235:56

---
232:   if (tool.toolName === undefined) {
233:     return [];
234:   }
235:   const directoryPatterns = channel.history?.toolBuilds[0]?.tool?.intelliJProperties?.directoryPatterns ?? [];
236:   const recentProjectsFilenames =
237:     channel.history?.toolBuilds[0]?.tool?.intelliJProperties?.recentProjectsFilenames ?? [];
238:   if (directoryPatterns.length === 0 || recentProjectsFilenames.length === 0) {
---
The recentProjects.xml files exist and contain valid recent project data. The directory structure and shell scripts are verified to be present and executable.

**Comment by bigplayer-ai** [comment]
# Raycast JetBrains Toolbox Extension Bug Report

## Summary
The Raycast JetBrains Toolbox extension throws a `TypeError` when attempting to fetch or display recent projects, even after setting the correct JetBrains shell scripts path.

---

## Steps to Reproduce

1. **Enable Shell Scripts in JetBrains Toolbox**  
   Configure the shell scripts path in JetBrains Toolbox settings:  
   ```
   ~/Library/Application\ Support/JetBrains/Toolbox/scripts
   ```

2. **Verify Shell Scripts Are Present**  
   Run the following command in the terminal:  
   ```bash
   ls -la ~/Library/Application\ Support/JetBrains/Toolbox/scripts
   ```  
   **Output:**
   ```
   -rwxr-xr-x@ 1 user  staff  421 clion
   -rwxr-xr-x@ 1 user  staff  428 idea
   -rwxr-xr-x@ 1 user  staff  422 pycharm
   ```

3. **Check for recentProjects.xml Files**  
   Ensure the recent projects XML files exist for the installed JetBrains IDEs:  
   ```bash
   ls -la ~/Library/Application\ Support/JetBrains/*/options/recentProjects.xml
   ```

4. **Set the Shell Scripts Path in Raycast Preferences**  
   Update the extension preferences to use the following path:  
   ```
   ~/Library/Application Support/JetBrains/Toolbox/scripts
   ```

5. **Attempt to Search for Recent Projects**  
   Use the extension to search for recent JetBrains projects.

---

## Expected Behavior
The extension should successfully display a list of recent projects for JetBrains IDEs.

---

## Actual Behavior
An unhandled exception occurs, and no projects are displayed. The following error is logged:

```
TypeError: Cannot read properties of undefined (reading '0')

b8:util.ts:235:56

---
232:   if (tool.toolName === undefined) {
233:     return [];
234:   }
235:   const directoryPatterns = channel.history?.toolBuilds[0]?.tool?.intelliJProperties?.directoryPatterns ?? [];
236:   const recentProjectsFilenames =
237:     channel.history?.toolBuilds[0]?.tool?.intelliJProperties?.recentProjectsFilenames ?? [];
238:   if (directoryPatterns.length === 0 || recentProjectsFilenames.length === 0) {
---
```

---

## Additional Information
- The `recentProjects.xml` files exist and contain valid recent project data.  
- The directory structure and shell scripts have been verified as present and executable.  
- Despite this, the extension fails to fetch or parse the project history.

--- 

Please investigate this issue further as it appears to be related to the extension's handling of recent project data.

**Comment by gdsmith** [comment]
Just to say, upgrading to the latest toolbox version should also fix this issue

**Comment by bigplayer-ai** [comment]
> Just to say, upgrading to the latest toolbox version should also fix this issue

I have JetBrains Toolbox 2.5.2.35332, macOS 15.2, arm64 and still the same problem...
Is there any other versions you recommend me to use?

**Comment by bigplayer-ai** [comment]
> Okay, I had assumed it was JB version related but it must actually be the version of the tool itself that is responsible for those files. What version of what IDEs are you using?

IntelliJ IDEA Ultimate 2024.3.1 (243.22562.145)
PyCharm Professional Edition 2024.3.1 (243.22562.180)
CLion 2024.3.1 (243.22562.155)

**Comment by gdsmith** [comment]
Weird, those look up to date. Wonder what the difference is. Anyway, PR was merged, please check if it fixed your issue.
