### ISSUE TITLE
[Cider] Couldn't connect to cider

### ISSUE THREAD

**Issue by misaka00251** [raycast/extensions#15910]
### Extension

https://www.raycast.com/feyli/cider

### Raycast Version

1.88.3

### macOS Version

15.1.1

### Description

I can't control Cider from Raycast.

![image](https://github.com/user-attachments/assets/5e5d47b3-9d63-4927-ac81-f52756038e30)

### Steps To Reproduce

1. Install Raycast.
2. Install the latest Cider version (2.5.0) and log in.
3. Open both.
4. Install the Cider plugin in Raycast.

### Current Behaviour

I can't control Cider from Raycast.

### Expected Behaviour

Control Cider from Raycast should work.

**Comment by feyli** [comment]
Hey, thank you for reporting this, I found the root cause of the issue and will be fixing this ASAP ;)

**Comment by feyli** [comment]
Hello and happy new year,
[I opened a PR](https://github.com/raycast/extensions/pull/16355), that should fix the issue and add new features that might be interesting.
Hope this gets approved quickly.

**Comment by misaka00251** [comment]
Thank you very much! Happy new year feyli!

**Comment by feyli** [comment]
Thank you! Well, it turns out it took way less time than expected. The new version is available ;)

**Comment by misaka00251** [comment]
Hmm, this is weird, I still can't control Cider despite removing this extension and reinstalling it again. And it seems I can't manually update the extension, seems like it's a feature of Raycast.

BTW, It didn't output an error on Cider this time:

![Image](https://github.com/user-attachments/assets/8fdd5bc4-68ac-47c6-98a2-b44e594de720)

I'm on Cider version 2.6.0.14 & Raycast 1.88.4. Also, I'm a Raycast & Cider newbie, should I enable something in both programs?

**Comment by feyli** [comment]
First of all, even though this shouldn't be a problem, can you please check you have the newest version of the Cider extension installed? If so, you're supposed to have the newly added "Queue" and "Synced Lyrics" commands. This means you have the latest version.

I checked on my side and the extension should properly work with the 2.6.0.14 version of Cider (as well as the latest PTBs)

Regarding the settings, you need to make sure the "WebSockets API" is enabled (this helps with the "Synced Lyrics" command) as seen below:
<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/7402cd69-215a-4091-9632-6ad2e2376404" />

Also, on the same screen, you should click "Manage" next to "Manage External Application Access to Cider" and make sure "Require API tokens" is turned off.
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/677c4a68-41d9-47e4-b102-1e9441fb6e2e" />

I will try to work on a way to include an access token in the extension settings for those Cider users who wish to keep the security option of requiring a token. In the meantime, you'll have to disable this security feature.

Does this help?

**Comment by feyli** [comment]
Yeah, just to add up to your issue. I'm pretty sure the authentication is the problem so my comment should fix your issue.

The extension shows an error message when it doesn’t get any response from Cider, which only happens if Cider is closed. If Cider is running but configured only to accept API calls with a token, it still sends a JSON response containing an error code. Commands that don’t need to process Cider’s output (action commands like Stop Playback, Play/Pause, Adjust Volume, etc.) don’t check this error. Instead, they just confirm that they received a response, assuming Cider is up and running.

Hope that's clear, this is why you were getting successful feedback.

**Comment by misaka00251** [comment]
> Also, on the same screen, you should click "Manage" next to "Manage External Application Access to Cider" and make sure "Require API tokens" is turned off. <img alt="Image" width="1624" src="https://private-user-images.githubusercontent.com/44325762/403375833-1c855901-cda1-43f8-aae4-95573b637df0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NDcwNjMsIm5iZiI6MTczNjk0Njc2MywicGF0aCI6Ii80NDMyNTc2Mi80MDMzNzU4MzMtMWM4NTU5MDEtY2RhMS00M2Y4LWFhZTQtOTU1NzNiNjM3ZGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDEzMTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3Zjg3NDcwYjUzZDRhNGI5OGRmZmM1Zjk1OTY2NGQyNmY5YmE3NTYxMzZlOTljOTM2NjMzODdhZjk4NTQ1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L3ZWln32CM8kKGWa95J9qhbxFuraO5Z7_7iCUcOhhto">
> 

Yes! The "Require API tokens" is automatically turned on. Turn this off fixed my issue. Thank you for your hard work!

**Comment by feyli** [comment]
Yeah, I figured it was probably automatically turned on.

I will very soon push a new update to fix a few things I found today while testing your issue. It will also include the option to use a token.

Thank you for reporting all of this and for using my extension, I really appreciate it :)

If you do not have any more questions, you may close the issue as resolved. I'll probably do it myself in a day anyway haha.

Take care!

**Comment by misaka00251** [comment]
Sure! 😄
