### ISSUE TITLE
[Music] Search for Artist and Song Title

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#4271]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

It would be great to be able to search artist and song title at the same time. With hip hop especially spelling can be a challenge on song names. Perhaps a pipe character could trigger splitting the string intro artist and song query.

For example: <artist search> | <song search>

Which would track with this AppleScript example

https://alvinalexander.com/blog/post/mac-os-x/search-for-song-in-itunes-library-using-applescript/

**Comment by Rawnly** [comment]
I'll add this to #4048

**Comment by Rawnly** [comment]
Hi @christianmagill this actually was implemented a while ago.
The current script is running the following 

```osascript
	set results to (every track whose name contains "${search}" or artist contains "${search}")
```

**Comment by christianmagill** [comment]
Hi @Rawnly,

You can currently search by artist OR track name, but you can't search for artist AND track name.

If you are searching for Michael Jackson's Bad for instance...

You could currently either search for "Michael Jackson", and scroll through all the Michael Jackson songs to find what you are looking for, or you could search for "Bad", and search through a bunch of songs that contain the word "Bad".

But if you split the query with a pipe character into two parts... you could search for "Jackson | Bad" and it would return

`set results to (every track whose name contains "Bad" and artist contains "Jackson")`

That's liable to return a much shorter list.

**Comment by Rawnly** [comment]
Ok, I understand your point, but I don't feel like an operator could be the solution here, since there's no way to document it outside of the command description or readme. I'll try via an action

**Comment by Rawnly** [comment]
Hey @christianmagill what do you think about this?

![CleanShot 2023-01-20 at 15 31 47@2x](https://user-images.githubusercontent.com/16429579/213723751-8a4a751c-03ab-4c66-a5cf-fbab23ed2211.png)
![CleanShot 2023-01-20 at 15 32 08@2x](https://user-images.githubusercontent.com/16429579/213723775-880614fc-6a17-483e-9aae-aa3c3838b43a.png)

I have to find a better name for the option :)

**Comment by christianmagill** [comment]
@Rawnly How do you determine what is the first part of the query and the second part?

**Comment by Rawnly** [comment]
what about a comma?

**Comment by Rawnly** [comment]
another option would be a simple query engine like the github issues one:  `Bad artist=michael jackson`

**Comment by christianmagill** [comment]
@Rawnly, Hm.. a comma would be a little more expected I guess but may be used in more song titles... That's why I was originally thinking of a pipe character because I don't see too many songs with that. The query would work, but would be a bit more typing I guess.

**Comment by christianmagill** [comment]
But I think with a query engine that's going to require more explanation than a pipe character.

**Comment by christianmagill** [comment]
@Rawnly, I'm unfamiliar with the stale status. Is this an idea that will just go into the backlog to be explored at a different time?

**Comment by danpalmer** [comment]
@christianmagill hey I've just edited the Apple Music extension to use the built-in search algorithm in the Music app. This should mean that you get the same results in Raycast using this extension as you would with the library search in the Music app. Do you think this would solve for your use-case?

Hopefully this should be merged and released soon. You can track it here: #5862

**Comment by christianmagill** [comment]
@danpalmer , Surprisingly it doesn't seem to. It seems the search works differently depending on whether you are searching your library or Apple Music. 

To recreate... Add album to library

https://music.apple.com/us/album/bad/559334659

Search in Music App for "Jackson Bad". It shows up both the album and track in an "Apple Music" search but no results are returned in a "Your Library" search.

**Comment by danpalmer** [comment]
@christianmagill strange, while I can't test this with that album specifically (Apple Music won't add it to my library at the moment), I can't reproduce this otherwise.

I used the example _Intro_ by _M83_. Searching for "m83 intro" returns that song as the top hit. This works in both the Your Library search, and in the new unreleased version of the Music extension for Raycast.

This doesn't work in the currently live version of the extension though, it's part of what I fixed.

**Comment by christianmagill** [comment]
Strange... I had the same issue... I added the album, but it only added a few tracks the first time. Now that I have the full album, "Jackson Bad" still doesn't work on "My Library" search, but "Bad Jackson" does. I think that gets close enough to what I'm looking for. Thanks!
