### ISSUE TITLE
[Warp Launch Configuration] The extension is launching multiple Warp instances

### ISSUE THREAD

**Issue by alessandro-newzoo** [raycast/extensions#6346]
### Extension

https://www.raycast.com/joetannenbaum/warp-launch-configuration

### Description

Hello, and thanks for this beautiful extension!

I have two issues that I believe can be both addressed with a single fix:

1. If Warp is closed, the extension will launch two windows, which is rather annoying
2. If Warp is open, the extension will still launch a new window, and so on each time you launch a new configuration from Raycast.

I believe changing the behavior so that it opens the configuration in a new tab instead of a new window would address both problems.

I'm not sure how you're handling this, but if you're using the AppleScript workaround, then you could send `⌘` + `T`:

```AppleScript
        tell application "System Events" to tell process "Warp"
	    keystroke "t" using {command down}
            delay 0.5
            -- ...rest of your code...
        end tell
```

### Steps To Reproduce

Already explained above

### Current Behaviour

The extension spawns a new window each time a configuration is launched

### Expected Behaviour

The extension should launch the configuration in a new tab instead

**Comment by alessandro-newzoo** [comment]
commenting to keep it open until acknowledged

**Comment by Moristotle** [comment]
@joetannenbaum - tagging for notification

**Comment by joetannenbaum** [comment]
Sorry for the delay here, this should be resolved by end of next week at the latest.

**Comment by alessandro-newzoo** [comment]
@joetannenbaum thank you SO much, and no need to apologize for free work ❤️

**Comment by alessandro-newzoo** [comment]
@joetannenbaum hi and thank you! 
My extensions are up to date, but it's still opening a new window every time. Perhaps the update didn't make it to the store yet?

<img width="1210" alt="image" src="https://github.com/raycast/extensions/assets/47320294/1bc1d0e2-327f-411f-bfe3-c23bcfd86817">

**Comment by joetannenbaum** [comment]
@alessandro-newzoo happy to investigate, just checking in that this is still happening?

**Comment by alessandro-newzoo** [comment]
hey @joetannenbaum sorry for the late reply, I was off!

Yes, both issues are still happening unfortunately.


https://github.com/raycast/extensions/assets/47320294/c8cc7eab-86c3-4900-a05e-6ca6fa28ce39

If I "check for extensions updates", it says I'm up to date:

<img width="244" alt="image" src="https://github.com/raycast/extensions/assets/47320294/96452303-953a-47fa-8c46-0adfbf738ee6">

Is this not happening to you?
