### ISSUE TITLE
Notion Page search not returning results

### ISSUE THREAD

**Issue by Ali-Parandeh** [raycast/extensions#690]
# Extension – [Notion](https://github.com/raycast/extensions/tree/main/extensions/notion)

Author: @HenriChabrand  

## Description

After creating a notion token with full permissions, the search command doesn't return anything and only shows no results found. Perhaps the notion API has changed?

<img width="803" alt="Screenshot 2022-01-16 at 12 47 08" src="https://user-images.githubusercontent.com/43654026/149660497-06e52eb4-f097-46f6-beaa-baf3c8264c93.png">

## Steps To Reproduce

1. Open search pages commands
2. Start typing

## The current behavior
Does not show anything - 

## The expected behavior
It should at least show the most recent pages in my notion

### Raycast version
Version: 1.27.0

**Comment by Ali-Parandeh** [comment]
Resolved the issue: Lack of documentation in the extension - The parent page of the pages I wanted to search must also be shared with the integration

https://stackoverflow.com/questions/69358435/notion-api-search-method-returns-nothing

**Comment by Ali-Parandeh** [comment]
Still not resolved - The problem is not from the extension but notion search API timing out. However, the extension does not handle timeout errors well to let the user know why the pages are not returned

<img width="1231" alt="Screenshot 2022-01-16 at 13 33 18" src="https://user-images.githubusercontent.com/43654026/149662176-3eabb67f-8164-4bc2-b8cc-a27d28fd2cb5.png">
.

**Comment by mattisssa** [comment]
Hey @HenriChabrand! 
Here is the new bug report to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by Ali-Parandeh** [comment]
This seems to be working now.

**Comment by JMitnik** [comment]
I still have this problem occur quite frequently. It does not seem like the extension supports searching in nested pages (if the parent page has all permissions required to search). Anyone encountered this before?

**Comment by kotarusv** [comment]
+1 This is one important extension.seach not working for although I followed documentation to create integration and added to extension

**Comment by dfrigon-20k** [comment]
I've added an integration and pasted the Notion Token in Raycast and after 1 full day, there is still no results at all! 

Does anyone figured the issue yet?

**Comment by kvenn** [comment]
+1. I'm also not seeing any results

**Comment by BryanSchuetz** [comment]
No results showing here either. I saw some mention of using O-Auth tokens, but no instructions on how to set that up—vs. the integration token
