### ISSUE TITLE
[Deepcast] Copy to clipboard not working

### ISSUE THREAD

**Issue by herrsilen** [raycast/extensions#9070]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

The extension has stopped copying the translated string into the clipboard, even though the On Translation Action is set to Copy to Clipboard.

### Steps To Reproduce

1. Open Deepcast
2. Translate a string
3. Try to paste into other application or view clipboard in Raycast

### Current Behaviour

The translation isn't copied to the clipboard.

### Expected Behaviour

The translation should be copied to the clipboard when set to do that in the extension settings.

**Comment by erics118** [comment]
Are you referring to the `Translate` command, or one of the `Translate into ...` commands?
It's not supported for `Translate` command, but it should be working for the `Translate into ...` commands

**Comment by erics118** [comment]
I think adding an action to copy the text to the cmd-k palette would be better. What do you think?

**Comment by herrsilen** [comment]
I'm referring to the Translate command. I'm pretty sure it has been working
before, since it's part of my workflow. However, adding an action to the
cmd-k palette with a shortcut would be super, too!

**Comment by erics118** [comment]
I've added support for it in #9083

**Comment by MonsterDeveloper** [comment]
Still doesn't work, unfortunately.

It seems to me that the issue is in [this line](https://github.com/raycast/extensions/blob/8de3f68427d54dda0a3429e68b65343782dbac34/extensions/deepcast/src/index.tsx#L70):

```ts
const response = await sendTranslateRequest({
    // ...
    onTranslateAction: "none",
  });
```

User's preferred action never gets to the translate function itself.

**Comment by erics118** [comment]
Although the original request was to copy on translate, I instead implemented it by adding a shortcut to copy the translated text, with `⌘.`

The UX for the onTranslateAction as "copy to clipboard" may make sense, but it wouldn't make as much sense for the "copy to clipboard" or the "paste" actions.
